# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "Gulpfile.js", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: Will Rebain | Blog
description: "A place for my thoughts"
keywords: 'will,willrebain,rebain,code,coder,coding,web,internet,online,mobile,program,programming,programmer,writer,writing,copy,copywriting,craft,crafter,crafting'
author:
  name: "Will Rebain"
  job_title: "Maker"
  location: "Columbia, SC"
  email: "willrebain@gmail.com"
  social_links:
    - name: facebook
      url: https://facebook.com/willrebain
    - name: github
      url: https://github.com/willrebain/willr-static-blog
    - name: instagram
      url: https://instagram.com/rebainwill
    - name: linkedin
      url: https://www.linkedin.com/in/william-rebain-4b2a457b
    - name: stackoverflow
      url:
    - name: twitter
      url: https://twitter.com/willrebain
    - name: vk
      url:
home:
  section1: <h1>William Rebain</h1>
  section2: <h2>Your guide to an excellent Internet presence</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/willrebain/willr-static-blog" title="View on GitHub"></a></div>
blog:
  cc_license: # A link to CC License of your choice, e.g. http://creativecommons.org/licenses/by-sa/4.0/.
  cc_license_image: # An image of your CC License, e.g. /assets/images/theme/cc-by-sa.png
  footer_content: Handcoded in Columbia, SC. 2017. w://r

disqus:
  shortname:
  public_key:
google_analytics:
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
